### PR TITLE
Use normal json decoding for header

### LINKED ISSUE #4: Header::from_base64 doesn't accept/"just discard" extra fields or differently ordered JSON
This header works:

    {
      "alg": "HS256",
      "typ": "JWT"
    }

This doesn't:

    {
      "typ": "JWT",
      "alg": "HS256"
    }

### PR DESCRIPTION
**Pull request by untitaker**
Fix #4

### CODE REVIEW

**Comment by Keats** [comment]
I was more thinking on hardcoding the 3 other orders for now as I'm not a big fan of discarding things silently.
Imo it's either the "cheap" way (harcoding the headers if it's only <10 like now) or allowing custom headers completely

**Comment by untitaker** [comment]
How would you implement custom headers? I thought of having a new type param `H: Part` for `encode` and `decode`

**Comment by Keats** [comment]
2 ways I can see:

- 1 method for encode/decode with a custom header in addition to the current on
- 1 method for both: instead of passing the algorithm when encoding you would pass a Header obj

If we follow the spec, we can do the following:
- add some Option to header for the ones referenced in http://self-issued.info/docs/draft-jones-json-web-token-01.html#ReservedHeaderParameterName 
- add a Default Header with alg=HS256 and everything else to None
- keep the constructor with the alg as param if we just want to create a basic header with another alg
- if you want to add some other params though you do it by hand after instantiation
- decode should still work the same

what do you think ?

**Comment by untitaker** [comment]
What if the user doesn't know e.g. the value of `cty` before decoding?

**Comment by Keats** [comment]
we'd need to return the header in decode as well, forgot to mention that.

`cty` seems to only be used when when the token is encrypted, which this crate doesn't support

**Comment by untitaker** [comment]
See #6

**Pull request closed without merging**
